#!/usr/bin/env node
// Generates src/lib/tokens.gen.css from src/lib/tokens.data.js — the Amber
// token contract (plan "Bản thiết kế Amber", item B1).
//
//   node scripts/gen-tokens.mjs            regenerate the CSS
//   node scripts/gen-tokens.mjs --check    exit 1 if the committed CSS is stale
//
// CI runs the --check form so a colour/scale change in tokens.data.js that
// wasn't regenerated fails the build, the same way check-i18n / check-versions
// guard their own single sources.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { tokens } from "../src/lib/tokens.data.js";

const OUT = fileURLToPath(new URL("../src/lib/tokens.gen.css", import.meta.url));
const CHECK = process.argv.includes("--check");

// Token key -> CSS custom-property name (only the multi-word ones need mapping).
const CSS_NAME = {
  ground: "ground",
  panel: "panel",
  panel2: "panel-2",
  edge: "edge",
  edgeSoft: "edge-soft",
  ink: "ink",
  inkMid: "ink-mid",
  inkMute: "ink-mute",
  amber: "amber",
  amberLine: "amber-line",
  biolum: "biolum",
  blood: "blood",
  moss: "moss",
};

const colorBlock = (set) =>
  Object.entries(set)
    .map(([k, v]) => `  --${CSS_NAME[k]}: ${v};`)
    .join("\n");

const semBlock = (set) =>
  Object.entries(set)
    .map(([k, v]) => `  --sem-${k}: ${v};`)
    .join("\n");

const durBlock = Object.entries(tokens.motion.dur)
  .map(([k, v]) => `  --dur-${k}: ${v}ms;`)
  .join("\n");

const radiusBlock = Object.entries(tokens.radius)
  .map(([k, v]) => `  --radius-${k}: ${v}px;`)
  .join("\n");

const css = `/* GENERATED by scripts/gen-tokens.mjs from src/lib/tokens.data.js — do NOT edit.
   Amber design tokens (B1 contract). Change tokens.data.js, then run:
     node scripts/gen-tokens.mjs
   The build runs \`node scripts/gen-tokens.mjs --check\` and fails on drift. */

:root {
${colorBlock(tokens.color.dark)}

  /* legacy aliases — 300+ components reference these names */
  --color-bg: var(--ground);
  --color-panel: var(--panel);
  --color-border: var(--edge);
  --color-text: var(--ink);
  --color-muted: var(--ink-mid);
  --color-accent: var(--amber);
  --color-player: #ff3b8b;

  --font-display: ${tokens.font.display};
  --font-body: ${tokens.font.body};
  --font-mono: ${tokens.font.mono};

${semBlock(tokens.semantic.default)}

${durBlock}
  --ease-out: ${tokens.motion.ease.out};
  --ease-in-out: ${tokens.motion.ease.inOut};

${radiusBlock}
}

/* Accessibility: deuteranopia-safe status colours. App.svelte sets
   data-color-profile from settings.ui.color_profile. */
:root[data-color-profile="deuteranopia"] {
${semBlock(tokens.semantic.deuteranopia)}
}

/* A9 skins. App.svelte sets data-skin from settings.skin; "obsidian" (the
   default) has no block and falls through to :root. Only the ground roles
   change — the legacy --color-* aliases point at these, so the whole window
   and the map chrome follow. */
:root[data-skin="bonefield"] {
${colorBlock(tokens.color.bonefield)}
}

:root[data-skin="biolum"] {
${colorBlock(tokens.color.biolum)}
}

/* Ready for a future light mode; inert until something sets it. */
:root[data-theme="light"] {
${colorBlock(tokens.color.light)}
  --color-player: #ff3b8b;
}
`;

if (CHECK) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    /* missing == stale */
  }
  // Compare line-ending-agnostic: a Windows checkout (or git autocrlf) can
  // hand us CRLF even though the generator only ever writes LF.
  if (current.replace(/\r\n/g, "\n") !== css.replace(/\r\n/g, "\n")) {
    console.error(
      "tokens.gen.css is out of date — run:  node scripts/gen-tokens.mjs",
    );
    process.exit(1);
  }
  console.log("tokens.gen.css is up to date");
} else {
  writeFileSync(OUT, css);
  console.log(`wrote ${OUT}`);
}
